iaasV2ApiAreaId.path=iaas/v2api/model_area_id.go
iaasV2ApiAreaId.replacementPath=v2api_model_area_id.go
iaasV2ApiAreaId.hash=b7425456c4633b2e8c0a61e9ab3b579e

iaasV1ApiAreaId.path=iaas/v1api/model_area_id.go
iaasV1ApiAreaId.replacementPath=v1api_model_area_id.go
iaasV1ApiAreaId.hash=a9d72364fec0794cab3b51f3680de584

iaasV2BetaApiAreaId.path="iaas/v2beta1api/model_area_id.go
iaasV2BetaApiAreaId.replacementPath=v2beta_model_area_id.go
iaasV2BetaApiAreaId.hash=bb5583419348ee95ebbde0b4133a36f0
