/*
 * STACKIT Automation Service API
 * API endpoints for automation management .
 *
 * The version of the OpenAPI document: 1beta.0
 * Contact: support@stackit.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package cloud.stackit.sdk.automation.v1betaapi.model;

import cloud.stackit.sdk.automation.v1betaapi.JSON;
import com.google.gson.Gson;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.annotations.SerializedName;
import com.google.gson.reflect.TypeToken;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.UUID;

/** CreateSnapshotsResult */
@javax.annotation.Generated(value = "JavaGenerator", comments = "Generator version: 7.19.0")
public class CreateSnapshotsResult {
	public static final String SERIALIZED_NAME_CREATED_SNAPSHOT_I_DS = "createdSnapshotIDs";

	@SerializedName(SERIALIZED_NAME_CREATED_SNAPSHOT_I_DS)
	@javax.annotation.Nullable private List<UUID> createdSnapshotIDs = new ArrayList<>();

	public static final String SERIALIZED_NAME_KIND = "kind";

	@SerializedName(SERIALIZED_NAME_KIND)
	@javax.annotation.Nonnull
	private String kind;

	public CreateSnapshotsResult() {}

	public CreateSnapshotsResult createdSnapshotIDs(
			@javax.annotation.Nullable List<UUID> createdSnapshotIDs) {
		this.createdSnapshotIDs = createdSnapshotIDs;
		return this;
	}

	public CreateSnapshotsResult addCreatedSnapshotIDsItem(UUID createdSnapshotIDsItem) {
		if (this.createdSnapshotIDs == null) {
			this.createdSnapshotIDs = new ArrayList<>();
		}
		this.createdSnapshotIDs.add(createdSnapshotIDsItem);
		return this;
	}

	/**
	 * Get createdSnapshotIDs
	 *
	 * @return createdSnapshotIDs
	 */
	@javax.annotation.Nullable public List<UUID> getCreatedSnapshotIDs() {
		return createdSnapshotIDs;
	}

	public void setCreatedSnapshotIDs(@javax.annotation.Nullable List<UUID> createdSnapshotIDs) {
		this.createdSnapshotIDs = createdSnapshotIDs;
	}

	public CreateSnapshotsResult kind(@javax.annotation.Nonnull String kind) {
		this.kind = kind;
		return this;
	}

	/**
	 * Get kind
	 *
	 * @return kind
	 */
	@javax.annotation.Nonnull
	public String getKind() {
		return kind;
	}

	public void setKind(@javax.annotation.Nonnull String kind) {
		this.kind = kind;
	}

	/**
	 * A container for additional, undeclared properties. This is a holder for any undeclared
	 * properties as specified with the 'additionalProperties' keyword in the OAS document.
	 */
	private Map<String, Object> additionalProperties;

	/**
	 * Set the additional (undeclared) property with the specified name and value. If the property
	 * does not already exist, create it otherwise replace it.
	 *
	 * @param key name of the property
	 * @param value value of the property
	 * @return the CreateSnapshotsResult instance itself
	 */
	public CreateSnapshotsResult putAdditionalProperty(String key, Object value) {
		if (this.additionalProperties == null) {
			this.additionalProperties = new HashMap<String, Object>();
		}
		this.additionalProperties.put(key, value);
		return this;
	}

	/**
	 * Return the additional (undeclared) property.
	 *
	 * @return a map of objects
	 */
	public Map<String, Object> getAdditionalProperties() {
		return additionalProperties;
	}

	/**
	 * Return the additional (undeclared) property with the specified name.
	 *
	 * @param key name of the property
	 * @return an object
	 */
	public Object getAdditionalProperty(String key) {
		if (this.additionalProperties == null) {
			return null;
		}
		return this.additionalProperties.get(key);
	}

	@Override
	public boolean equals(Object o) {
		if (this == o) {
			return true;
		}
		if (o == null || getClass() != o.getClass()) {
			return false;
		}
		CreateSnapshotsResult createSnapshotsResult = (CreateSnapshotsResult) o;
		return Objects.equals(this.createdSnapshotIDs, createSnapshotsResult.createdSnapshotIDs)
				&& Objects.equals(this.kind, createSnapshotsResult.kind)
				&& Objects.equals(
						this.additionalProperties, createSnapshotsResult.additionalProperties);
	}

	@Override
	public int hashCode() {
		return Objects.hash(createdSnapshotIDs, kind, additionalProperties);
	}

	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append("class CreateSnapshotsResult {\n");
		sb.append("    createdSnapshotIDs: ")
				.append(toIndentedString(createdSnapshotIDs))
				.append("\n");
		sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
		sb.append("    additionalProperties: ")
				.append(toIndentedString(additionalProperties))
				.append("\n");
		sb.append("}");
		return sb.toString();
	}

	/**
	 * Convert the given object to string with each line indented by 4 spaces (except the first
	 * line).
	 */
	private String toIndentedString(Object o) {
		if (o == null) {
			return "null";
		}
		return o.toString().replace("\n", "\n    ");
	}

	public static HashSet<String> openapiFields;
	public static HashSet<String> openapiRequiredFields;

	static {
		// a set of all properties/fields (JSON key names)
		openapiFields = new HashSet<String>(Arrays.asList("createdSnapshotIDs", "kind"));

		// a set of required properties/fields (JSON key names)
		openapiRequiredFields = new HashSet<String>(Arrays.asList("kind"));
	}

	/**
	 * Validates the JSON Element and throws an exception if issues found
	 *
	 * @param jsonElement JSON Element
	 * @throws IOException if the JSON Element is invalid with respect to CreateSnapshotsResult
	 */
	public static void validateJsonElement(JsonElement jsonElement) throws IOException {
		if (jsonElement == null) {
			if (!CreateSnapshotsResult.openapiRequiredFields
					.isEmpty()) { // has required fields but JSON element is null
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field(s) %s in CreateSnapshotsResult is not found in the empty JSON string",
								CreateSnapshotsResult.openapiRequiredFields.toString()));
			}
		}

		// check to make sure all required properties/fields are present in the JSON string
		for (String requiredField : CreateSnapshotsResult.openapiRequiredFields) {
			if (jsonElement.getAsJsonObject().get(requiredField) == null) {
				throw new IllegalArgumentException(
						String.format(
								java.util.Locale.ROOT,
								"The required field `%s` is not found in the JSON string: %s",
								requiredField,
								jsonElement.toString()));
			}
		}
		JsonObject jsonObj = jsonElement.getAsJsonObject();
		// ensure the optional json data is an array if present
		if (jsonObj.get("createdSnapshotIDs") != null
				&& !jsonObj.get("createdSnapshotIDs").isJsonNull()
				&& !jsonObj.get("createdSnapshotIDs").isJsonArray()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `createdSnapshotIDs` to be an array in the JSON string but got `%s`",
							jsonObj.get("createdSnapshotIDs").toString()));
		}
		if (!jsonObj.get("kind").isJsonPrimitive()) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `kind` to be a primitive type in the JSON string but got `%s`",
							jsonObj.get("kind").toString()));
		}
		// OVERRIDE START: this if block fixes oneOf issues
		if (!"CreateSnapshotsResult".equals(jsonObj.get("kind").getAsString())) {
			throw new IllegalArgumentException(
					String.format(
							java.util.Locale.ROOT,
							"Expected the field `kind` to have value `CreateSnapshotsResult` but got `%s`",
							jsonObj.get("kind").toString()));
		}
		// OVERRIDE END: this if block fixes oneOf issues
	}

	public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
		@SuppressWarnings("unchecked")
		@Override
		public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
			if (!CreateSnapshotsResult.class.isAssignableFrom(type.getRawType())) {
				return null; // this class only serializes 'CreateSnapshotsResult' and its subtypes
			}
			final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
			final TypeAdapter<CreateSnapshotsResult> thisAdapter =
					gson.getDelegateAdapter(this, TypeToken.get(CreateSnapshotsResult.class));

			return (TypeAdapter<T>)
					new TypeAdapter<CreateSnapshotsResult>() {
						@Override
						public void write(JsonWriter out, CreateSnapshotsResult value)
								throws IOException {
							JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
							obj.remove("additionalProperties");
							// serialize additional properties
							if (value.getAdditionalProperties() != null) {
								for (Map.Entry<String, Object> entry :
										value.getAdditionalProperties().entrySet()) {
									if (entry.getValue() instanceof String)
										obj.addProperty(entry.getKey(), (String) entry.getValue());
									else if (entry.getValue() instanceof Number)
										obj.addProperty(entry.getKey(), (Number) entry.getValue());
									else if (entry.getValue() instanceof Boolean)
										obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
									else if (entry.getValue() instanceof Character)
										obj.addProperty(
												entry.getKey(), (Character) entry.getValue());
									else {
										JsonElement jsonElement = gson.toJsonTree(entry.getValue());
										if (jsonElement.isJsonArray()) {
											obj.add(entry.getKey(), jsonElement.getAsJsonArray());
										} else {
											obj.add(entry.getKey(), jsonElement.getAsJsonObject());
										}
									}
								}
							}
							elementAdapter.write(out, obj);
						}

						@Override
						public CreateSnapshotsResult read(JsonReader in) throws IOException {
							JsonElement jsonElement = elementAdapter.read(in);
							validateJsonElement(jsonElement);
							JsonObject jsonObj = jsonElement.getAsJsonObject();
							// store additional fields in the deserialized instance
							CreateSnapshotsResult instance = thisAdapter.fromJsonTree(jsonObj);
							for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
								if (!openapiFields.contains(entry.getKey())) {
									if (entry.getValue().isJsonPrimitive()) { // primitive type
										if (entry.getValue().getAsJsonPrimitive().isString())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsString());
										else if (entry.getValue().getAsJsonPrimitive().isNumber())
											instance.putAdditionalProperty(
													entry.getKey(), entry.getValue().getAsNumber());
										else if (entry.getValue().getAsJsonPrimitive().isBoolean())
											instance.putAdditionalProperty(
													entry.getKey(),
													entry.getValue().getAsBoolean());
										else
											throw new IllegalArgumentException(
													String.format(
															java.util.Locale.ROOT,
															"The field `%s` has unknown primitive type. Value: %s",
															entry.getKey(),
															entry.getValue().toString()));
									} else if (entry.getValue().isJsonArray()) {
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), List.class));
									} else { // JSON object
										instance.putAdditionalProperty(
												entry.getKey(),
												gson.fromJson(entry.getValue(), HashMap.class));
									}
								}
							}
							return instance;
						}
					}.nullSafe();
		}
	}

	/**
	 * Create an instance of CreateSnapshotsResult given an JSON string
	 *
	 * @param jsonString JSON string
	 * @return An instance of CreateSnapshotsResult
	 * @throws IOException if the JSON string is invalid with respect to CreateSnapshotsResult
	 */
	public static CreateSnapshotsResult fromJson(String jsonString) throws IOException {
		return JSON.getGson().fromJson(jsonString, CreateSnapshotsResult.class);
	}

	/**
	 * Convert an instance of CreateSnapshotsResult to an JSON string
	 *
	 * @return JSON string
	 */
	public String toJson() {
		return JSON.getGson().toJson(this);
	}
}
