iaasV2AlphaApiRouteDestinationCIDRv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/DestinationCIDRv4.java
iaasV2AlphaApiRouteDestinationCIDRv4.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_destinationCIDRv4.java
iaasV2AlphaApiRouteDestinationCIDRv4.hash=61c00060b5f19d949ef6f2c6cd82a13a

iaasV2AlphaApiRouteDestinationCIDRv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/DestinationCIDRv6.java
iaasV2AlphaApiRouteDestinationCIDRv6.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_destinationCIDRv6.java
iaasV2AlphaApiRouteDestinationCIDRv6.hash=9e47a4ea974f9080093a6c9d2e615446

iaasV2AlphaApiNexthopIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopIPv4.java
iaasV2AlphaApiNexthopIPv4.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopIPv4.java
iaasV2AlphaApiNexthopIPv4.hash=2ea5d1b96781197503206c2f7c21e793

iaasV2AlphaApiNexthopIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopIPv6.java
iaasV2AlphaApiNexthopIPv6.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopIPv6.java
iaasV2AlphaApiNexthopIPv6.hash=c81d6973112f919bc2a7d119edc30ac7

iaasV2AlphaApiNexthopBlackhole.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopBlackhole.java
iaasV2AlphaApiNexthopBlackhole.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopBlackhole.java
iaasV2AlphaApiNexthopBlackhole.hash=ae20d347b1ac740c33ecc3d4ee42c9c9

iaasV2AlphaApiNexthopInternet.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopInternet.java
iaasV2AlphaApiNexthopInternet.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopInternet.java
iaasV2AlphaApiNexthopInternet.hash=c56c0bab9c1772eacec3638d52af8aaa

iaasV2AlphaApiVPCNetworkRangIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/VPCNetworkRangeIPv4.java
iaasV2AlphaApiVPCNetworkRangIPv4.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_vpcNetworkRangeIPv4.java
iaasV2AlphaApiVPCNetworkRangIPv4.hash=40609d6eae20476897b5e5be0de3d3fc

iaasV2AlphaApiVPCNetworkRangIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/VPCNetworkRangeIPv6.java
iaasV2AlphaApiVPCNetworkRangIPv6.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_vpcNetworkRangeIPv6.java
iaasV2AlphaApiVPCNetworkRangIPv6.hash=d71c09fe5cb8b70c47888681f8d8d7a1

iaasV2RoutDestinationCIDRv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/DestinationCIDRv4.java
iaasV2RoutDestinationCIDRv4.replacementPath=iaas/v2api/DestinationCIDRv4.java
iaasV2RoutDestinationCIDRv4.hash=b79f08064422b8040d7f218c1f20957e

iaasV2RoutDestinationCIDRv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/DestinationCIDRv6.java
iaasV2RoutDestinationCIDRv6.replacementPath=iaas/v2api/DestinationCIDRv6.java
iaasV2RoutDestinationCIDRv6.hash=8037f4ec45cbfde8445300d968ee7ed8

iaasV2RoutNexthopIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopIPv4.java
iaasV2RoutNexthopIPv4.replacementPath=iaas/v2api/NexthopIPv4.java
iaasV2RoutNexthopIPv4.hash=6fc66b4640d7542ea554c1a3b722867a

iaasV2RoutNexthopIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopIPv6.java
iaasV2RoutNexthopIPv6.replacementPath=iaas/v2api/NexthopIPv6.java
iaasV2RoutNexthopIPv6.hash=c94522b47ce6bb9118a7f984c4e21b5e

iaasV2RoutNexthopBlackhole.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopBlackhole.java
iaasV2RoutNexthopBlackhole.replacementPath=iaas/v2api/NexthopBlackhole.java
iaasV2RoutNexthopBlackhole.hash=d96000d32e36ac4b4a4d6b593d13baf7

iaasV2RoutNexthopInternet.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopInternet.java
iaasV2RoutNexthopInternet.replacementPath=iaas/v2api/NexthopInternet.java
iaasV2RoutNexthopInternet.hash=63be65c5560e58509820bde50251ef1b

iaasV2betaRoutDestinationCIDRv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/DestinationCIDRv4.java
iaasV2betaRoutDestinationCIDRv4.replacementPath=iaas/v2beta1api/DestinationCIDRv4.java
iaasV2betaRoutDestinationCIDRv4.hash=aed7d0c5159bed1891cafa3695507638

iaasV2betaRoutDestinationCIDRv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/DestinationCIDRv6.java
iaasV2betaRoutDestinationCIDRv6.replacementPath=iaas/v2beta1api/DestinationCIDRv6.java
iaasV2betaRoutDestinationCIDRv6.hash=93520dfa24f87b9c134e2cef7921234d

iaasV2betaRoutNexthopIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopIPv4.java
iaasV2betaRoutNexthopIPv4.replacementPath=iaas/v2beta1api/NexthopIPv4.java
iaasV2betaRoutNexthopIPv4.hash=95ff4343f14bf67c76939eb796a51b44

iaasV2betaRoutNexthopIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopIPv6.java
iaasV2betaRoutNexthopIPv6.replacementPath=iaas/v2beta1api/NexthopIPv6.java
iaasV2betaRoutNexthopIPv6.hash=69421ea20ef9d68892a965c3914547fe

iaasV2betaRoutNexthopBlackhole.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopBlackhole.java
iaasV2betaRoutNexthopBlackhole.replacementPath=iaas/v2beta1api/NexthopBlackhole.java
iaasV2betaRoutNexthopBlackhole.hash=eaab6cd1a5e3c2edf429534565b018a6

iaasV2betaRoutNexthopInternet.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopInternet.java
iaasV2betaRoutNexthopInternet.replacementPath=iaas/v2beta1api/NexthopInternet.java
iaasV2betaRoutNexthopInternet.hash=fd3f5a71d16855c721c0bb5852550538
