automationV1BetaApiCreateSnapshotsResult.path=automation/src/main/java/cloud/stackit/sdk/automation/v1betaapi/model/CreateSnapshotsResult.java
automationV1BetaApiCreateSnapshotsResult.replacementPath=automation/v1betaapi/CreateSnapshotsResult.java
automationV1BetaApiCreateSnapshotsResult.hash=ac555ba72060b40e75893ee1b0c6e3c5

automationV1BetaApiGetVolumeIDsResult.path=automation/src/main/java/cloud/stackit/sdk/automation/v1betaapi/model/GetVolumeIDsResult.java
automationV1BetaApiGetVolumeIDsResult.replacementPath=automation/v1betaapi/GetVolumeIDsResult.java
automationV1BetaApiGetVolumeIDsResult.hash=d27467d67db516d0cba7c18d1fe4b216

automationV1BetaApiSnapshotRetentionPolicyCount.path=automation/src/main/java/cloud/stackit/sdk/automation/v1betaapi/model/SnapshotRetentionPolicyCount.java
automationV1BetaApiSnapshotRetentionPolicyCount.replacementPath=automation/v1betaapi/SnapshotRetentionPolicyCount.java
automationV1BetaApiSnapshotRetentionPolicyCount.hash=4adcfe9d80ce524dd0a01d18ec0e6410

automationV1BetaApiSnapshotRetentionPolicyIndefinitely.path=automation/src/main/java/cloud/stackit/sdk/automation/v1betaapi/model/SnapshotRetentionPolicyIndefinitely.java
automationV1BetaApiSnapshotRetentionPolicyIndefinitely.replacementPath=automation/v1betaapi/SnapshotRetentionPolicyIndefinitely.java
automationV1BetaApiSnapshotRetentionPolicyIndefinitely.hash=f441b4be83c6368675c8b627da2b375a

iaasV2AlphaApiRouteDestinationCIDRv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/DestinationCIDRv4.java
iaasV2AlphaApiRouteDestinationCIDRv4.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_destinationCIDRv4.java
iaasV2AlphaApiRouteDestinationCIDRv4.hash=fa15bacf2804d8d04d06a146032897ee

iaasV2AlphaApiRouteDestinationCIDRv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/DestinationCIDRv6.java
iaasV2AlphaApiRouteDestinationCIDRv6.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_destinationCIDRv6.java
iaasV2AlphaApiRouteDestinationCIDRv6.hash=c4df9184d4c8fc47dfef424b236d5c6c

iaasV2AlphaApiNexthopIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopIPv4.java
iaasV2AlphaApiNexthopIPv4.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopIPv4.java
iaasV2AlphaApiNexthopIPv4.hash=eb8789750e356abf359466d6c62dbe15

iaasV2AlphaApiNexthopIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopIPv6.java
iaasV2AlphaApiNexthopIPv6.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopIPv6.java
iaasV2AlphaApiNexthopIPv6.hash=b649d826bc349e47ecc8c994f24d5385

iaasV2AlphaApiNexthopBlackhole.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopBlackhole.java
iaasV2AlphaApiNexthopBlackhole.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopBlackhole.java
iaasV2AlphaApiNexthopBlackhole.hash=74d17cc84bbdfc99dfc19ff1fcff80b6

iaasV2AlphaApiNexthopInternet.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopInternet.java
iaasV2AlphaApiNexthopInternet.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_nexthopInternet.java
iaasV2AlphaApiNexthopInternet.hash=422e4bb42cbded48e57f35a35a7e7a81

iaasV2AlphaApiVPCNetworkRangIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/VPCNetworkRangeIPv4.java
iaasV2AlphaApiVPCNetworkRangIPv4.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_vpcNetworkRangeIPv4.java
iaasV2AlphaApiVPCNetworkRangIPv4.hash=2c829e3991dc05bd4fde6383614a247a

iaasV2AlphaApiVPCNetworkRangIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/VPCNetworkRangeIPv6.java
iaasV2AlphaApiVPCNetworkRangIPv6.replacementPath=iaas/v2alpha1api/iaas_v2alpha_model_vpcNetworkRangeIPv6.java
iaasV2AlphaApiVPCNetworkRangIPv6.hash=b707bf15b842ad30cc998c08ed8076a6

iaasV2RouteDestinationCIDRv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/DestinationCIDRv4.java
iaasV2RouteDestinationCIDRv4.replacementPath=iaas/v2api/DestinationCIDRv4.java
iaasV2RouteDestinationCIDRv4.hash=075f620c50a65067896860f73ae9d05d

iaasV2RouteDestinationCIDRv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/DestinationCIDRv6.java
iaasV2RouteDestinationCIDRv6.replacementPath=iaas/v2api/DestinationCIDRv6.java
iaasV2RouteDestinationCIDRv6.hash=a0ab059ef4a66067713c2099d2a2e68b

iaasV2RouteNexthopIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopIPv4.java
iaasV2RouteNexthopIPv4.replacementPath=iaas/v2api/NexthopIPv4.java
iaasV2RouteNexthopIPv4.hash=9fe4f34934b1ffc73aff39bb550a9d0a

iaasV2RouteNexthopIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopIPv6.java
iaasV2RouteNexthopIPv6.replacementPath=iaas/v2api/NexthopIPv6.java
iaasV2RouteNexthopIPv6.hash=573618660397c921aec05425f364866b

iaasV2RouteNexthopBlackhole.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopBlackhole.java
iaasV2RouteNexthopBlackhole.replacementPath=iaas/v2api/NexthopBlackhole.java
iaasV2RouteNexthopBlackhole.hash=68a7d98a6ff2f4b65766da1709d7166b

iaasV2RouteNexthopInternet.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2api/model/NexthopInternet.java
iaasV2RouteNexthopInternet.replacementPath=iaas/v2api/NexthopInternet.java
iaasV2RouteNexthopInternet.hash=9108c0884deabbff4094da27803ac7b4

iaasV2betaRouteDestinationCIDRv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/DestinationCIDRv4.java
iaasV2betaRouteDestinationCIDRv4.replacementPath=iaas/v2beta1api/DestinationCIDRv4.java
iaasV2betaRouteDestinationCIDRv4.hash=821e2278c7604b4c3d2f6e72e8d9a365

iaasV2betaRouteDestinationCIDRv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/DestinationCIDRv6.java
iaasV2betaRouteDestinationCIDRv6.replacementPath=iaas/v2beta1api/DestinationCIDRv6.java
iaasV2betaRouteDestinationCIDRv6.hash=a55c6d03e973013bd01557410fdee6ad

iaasV2betaRouteNexthopIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopIPv4.java
iaasV2betaRouteNexthopIPv4.replacementPath=iaas/v2beta1api/NexthopIPv4.java
iaasV2betaRouteNexthopIPv4.hash=53995f795a7ec9288b6cc9c86642d4e2

iaasV2betaRouteNexthopIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopIPv6.java
iaasV2betaRouteNexthopIPv6.replacementPath=iaas/v2beta1api/NexthopIPv6.java
iaasV2betaRouteNexthopIPv6.hash=ec029362fe0f289ce8732183cacc6855

iaasV2betaRouteNexthopBlackhole.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopBlackhole.java
iaasV2betaRouteNexthopBlackhole.replacementPath=iaas/v2beta1api/NexthopBlackhole.java
iaasV2betaRouteNexthopBlackhole.hash=70789628d5bebe2dced654f2833e028d

iaasV2betaRouteNexthopInternet.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2beta1api/model/NexthopInternet.java
iaasV2betaRouteNexthopInternet.replacementPath=iaas/v2beta1api/NexthopInternet.java
iaasV2betaRouteNexthopInternet.hash=ae56426056a1f33dee92236808bf4b90
