iaasV2AlphaApiRouteDestinationCIDRv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/DestinationCIDRv4.java
iaasV2AlphaApiRouteDestinationCIDRv4.replacementPath=iaas_v2alpha_model_destinationCIDRv4.java
iaasV2AlphaApiRouteDestinationCIDRv4.hash=61c00060b5f19d949ef6f2c6cd82a13a

iaasV2AlphaApiRouteDestinationCIDRv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/DestinationCIDRv6.java
iaasV2AlphaApiRouteDestinationCIDRv6.replacementPath=iaas_v2alpha_model_destinationCIDRv6.java
iaasV2AlphaApiRouteDestinationCIDRv6.hash=9e47a4ea974f9080093a6c9d2e615446

iaasV2AlphaApiNexthopIPv4.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopIPv4.java
iaasV2AlphaApiNexthopIPv4.replacementPath=iaas_v2alpha_model_nexthopIPv4.java
iaasV2AlphaApiNexthopIPv4.hash=2ea5d1b96781197503206c2f7c21e793

iaasV2AlphaApiNexthopIPv6.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopIPv6.java
iaasV2AlphaApiNexthopIPv6.replacementPath=iaas_v2alpha_model_nexthopIPv6.java
iaasV2AlphaApiNexthopIPv6.hash=c81d6973112f919bc2a7d119edc30ac7

iaasV2AlphaApiNexthopBlackhole.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopBlackhole.java
iaasV2AlphaApiNexthopBlackhole.replacementPath=iaas_v2alpha_model_nexthopBlackhole.java
iaasV2AlphaApiNexthopBlackhole.hash=ae20d347b1ac740c33ecc3d4ee42c9c9

iaasV2AlphaApiNexthopInternet.path=iaas/src/main/java/cloud/stackit/sdk/iaas/v2alpha1api/model/NexthopInternet.java
iaasV2AlphaApiNexthopInternet.replacementPath=iaas_v2alpha_model_nexthopInternet.java
iaasV2AlphaApiNexthopInternet.hash=c56c0bab9c1772eacec3638d52af8aaa
