/*
 * STACKIT IaaS API
 * This API allows you to create and modify IaaS resources.
 *
 * The version of the OpenAPI document: 2alpha1
 * Contact: stackit-iaas@mail.schwarz
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package cloud.stackit.sdk.iaas.v2alpha1api.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import cloud.stackit.sdk.iaas.v2alpha1api.JSON;

/**
 * Contains the IPv6 properties of a VPC network range.
 */
@javax.annotation.Generated(value = "JavaGenerator", comments = "Generator version: 7.19.0")
public class VPCNetworkRangeIPv6 {
  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  @javax.annotation.Nullable
  private String description;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  @javax.annotation.Nullable
  private UUID id;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  @javax.annotation.Nullable
  private Object labels;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  @javax.annotation.Nullable
  private String status;

  public static final String SERIALIZED_NAME_UPDATED_AT = "updatedAt";
  @SerializedName(SERIALIZED_NAME_UPDATED_AT)
  @javax.annotation.Nullable
  private OffsetDateTime updatedAt;

  public static final String SERIALIZED_NAME_DEFAULT_PREFIX_LEN = "defaultPrefixLen";
  @SerializedName(SERIALIZED_NAME_DEFAULT_PREFIX_LEN)
  @javax.annotation.Nullable
  private Long defaultPrefixLen;

  /**
   * Gets or Sets ipVersion
   */
  @JsonAdapter(IpVersionEnum.Adapter.class)
  public enum IpVersionEnum {
    IPV6("ipv6"),
    
    UNKNOWN_DEFAULT_OPEN_API("unknown_default_open_api");

    private String value;

    IpVersionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static IpVersionEnum fromValue(String value) {
      for (IpVersionEnum b : IpVersionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      return UNKNOWN_DEFAULT_OPEN_API;
    }

    public static class Adapter extends TypeAdapter<IpVersionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final IpVersionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public IpVersionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return IpVersionEnum.fromValue(value);
      }
    }

    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      String value = jsonElement.getAsString();
      IpVersionEnum.fromValue(value);
    }
  }

  public static final String SERIALIZED_NAME_IP_VERSION = "ipVersion";
  @SerializedName(SERIALIZED_NAME_IP_VERSION)
  @javax.annotation.Nonnull
  private IpVersionEnum ipVersion;

  public static final String SERIALIZED_NAME_MAX_PREFIX_LEN = "maxPrefixLen";
  @SerializedName(SERIALIZED_NAME_MAX_PREFIX_LEN)
  @javax.annotation.Nullable
  private Long maxPrefixLen;

  public static final String SERIALIZED_NAME_MIN_PREFIX_LEN = "minPrefixLen";
  @SerializedName(SERIALIZED_NAME_MIN_PREFIX_LEN)
  @javax.annotation.Nullable
  private Long minPrefixLen;

  public static final String SERIALIZED_NAME_NAMESERVERS = "nameservers";
  @SerializedName(SERIALIZED_NAME_NAMESERVERS)
  @javax.annotation.Nullable
  private List<String> nameservers;

  public static final String SERIALIZED_NAME_PREFIX = "prefix";
  @SerializedName(SERIALIZED_NAME_PREFIX)
  @javax.annotation.Nonnull
  private String prefix;

  public VPCNetworkRangeIPv6() {
  }

  public VPCNetworkRangeIPv6(
     OffsetDateTime createdAt, 
     UUID id, 
     OffsetDateTime updatedAt
  ) {
    this();
    this.createdAt = createdAt;
    this.id = id;
    this.updatedAt = updatedAt;
  }

  /**
   * Date-time when resource was created.
   * @return createdAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }



  public VPCNetworkRangeIPv6 description(@javax.annotation.Nullable String description) {
    this.description = description;
    return this;
  }

  /**
   * Description Object. Allows string up to 255 Characters.
   * @return description
   */
  @javax.annotation.Nullable
  public String getDescription() {
    return description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = description;
  }


  /**
   * Universally Unique Identifier (UUID).
   * @return id
   */
  @javax.annotation.Nullable
  public UUID getId() {
    return id;
  }



  public VPCNetworkRangeIPv6 labels(@javax.annotation.Nullable Object labels) {
    this.labels = labels;
    return this;
  }

  /**
   * Object that represents the labels of an object. Regex for keys: &#x60;^(?&#x3D;.{1,63}$)([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]$&#x60;. Regex for values: &#x60;^(?&#x3D;.{0,63}$)(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])*$&#x60;. Providing a &#x60;null&#x60; value for a key will remove that key. The &#x60;stackit-&#x60; prefix is reserved and cannot be used for Keys.
   * @return labels
   */
  @javax.annotation.Nullable
  public Object getLabels() {
    return labels;
  }

  public void setLabels(@javax.annotation.Nullable Object labels) {
    this.labels = labels;
  }


  public VPCNetworkRangeIPv6 status(@javax.annotation.Nullable String status) {
    this.status = status;
    return this;
  }

  /**
   * The state of a resource object. Possible values: &#x60;CREATING&#x60;, &#x60;CREATED&#x60;, &#x60;DELETING&#x60;, &#x60;DELETED&#x60;, &#x60;FAILED&#x60;, &#x60;UPDATED&#x60;, &#x60;UPDATING&#x60;.
   * @return status
   */
  @javax.annotation.Nullable
  public String getStatus() {
    return status;
  }

  public void setStatus(@javax.annotation.Nullable String status) {
    this.status = status;
  }


  /**
   * Date-time when resource was last updated.
   * @return updatedAt
   */
  @javax.annotation.Nullable
  public OffsetDateTime getUpdatedAt() {
    return updatedAt;
  }



  public VPCNetworkRangeIPv6 defaultPrefixLen(@javax.annotation.Nullable Long defaultPrefixLen) {
    this.defaultPrefixLen = defaultPrefixLen;
    return this;
  }

  /**
   * The ipv6 prefix lengths for subnets or network ranges in the VPC.
   * minimum: 0
   * maximum: 128
   * @return defaultPrefixLen
   */
  @javax.annotation.Nullable
  public Long getDefaultPrefixLen() {
    return defaultPrefixLen;
  }

  public void setDefaultPrefixLen(@javax.annotation.Nullable Long defaultPrefixLen) {
    this.defaultPrefixLen = defaultPrefixLen;
  }


  public VPCNetworkRangeIPv6 ipVersion(@javax.annotation.Nonnull IpVersionEnum ipVersion) {
    this.ipVersion = ipVersion;
    return this;
  }

  /**
   * Get ipVersion
   * @return ipVersion
   */
  @javax.annotation.Nonnull
  public IpVersionEnum getIpVersion() {
    return ipVersion;
  }

  public void setIpVersion(@javax.annotation.Nonnull IpVersionEnum ipVersion) {
    this.ipVersion = ipVersion;
  }


  public VPCNetworkRangeIPv6 maxPrefixLen(@javax.annotation.Nullable Long maxPrefixLen) {
    this.maxPrefixLen = maxPrefixLen;
    return this;
  }

  /**
   * The ipv6 prefix lengths for subnets or network ranges in the VPC.
   * minimum: 0
   * maximum: 128
   * @return maxPrefixLen
   */
  @javax.annotation.Nullable
  public Long getMaxPrefixLen() {
    return maxPrefixLen;
  }

  public void setMaxPrefixLen(@javax.annotation.Nullable Long maxPrefixLen) {
    this.maxPrefixLen = maxPrefixLen;
  }


  public VPCNetworkRangeIPv6 minPrefixLen(@javax.annotation.Nullable Long minPrefixLen) {
    this.minPrefixLen = minPrefixLen;
    return this;
  }

  /**
   * The ipv6 prefix lengths for subnets or network ranges in the VPC.
   * minimum: 0
   * maximum: 128
   * @return minPrefixLen
   */
  @javax.annotation.Nullable
  public Long getMinPrefixLen() {
    return minPrefixLen;
  }

  public void setMinPrefixLen(@javax.annotation.Nullable Long minPrefixLen) {
    this.minPrefixLen = minPrefixLen;
  }


  public VPCNetworkRangeIPv6 nameservers(@javax.annotation.Nullable List<String> nameservers) {
    this.nameservers = nameservers;
    return this;
  }

  public VPCNetworkRangeIPv6 addNameserversItem(String nameserversItem) {
    if (this.nameservers == null) {
      this.nameservers = new ArrayList<>();
    }
    this.nameservers.add(nameserversItem);
    return this;
  }

  /**
   * A list containing DNS Servers/Nameservers for IPv6.
   * @return nameservers
   */
  @javax.annotation.Nullable
  public List<String> getNameservers() {
    return nameservers;
  }

  public void setNameservers(@javax.annotation.Nullable List<String> nameservers) {
    this.nameservers = nameservers;
  }


  public VPCNetworkRangeIPv6 prefix(@javax.annotation.Nonnull String prefix) {
    this.prefix = prefix;
    return this;
  }

  /**
   * Classless Inter-Domain Routing (CIDR) for IPv6.
   * @return prefix
   */
  @javax.annotation.Nonnull
  public String getPrefix() {
    return prefix;
  }

  public void setPrefix(@javax.annotation.Nonnull String prefix) {
    this.prefix = prefix;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the VPCNetworkRangeIPv6 instance itself
   */
  public VPCNetworkRangeIPv6 putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VPCNetworkRangeIPv6 vpCNetworkRangeIPv6 = (VPCNetworkRangeIPv6) o;
    return Objects.equals(this.createdAt, vpCNetworkRangeIPv6.createdAt) &&
        Objects.equals(this.description, vpCNetworkRangeIPv6.description) &&
        Objects.equals(this.id, vpCNetworkRangeIPv6.id) &&
        Objects.equals(this.labels, vpCNetworkRangeIPv6.labels) &&
        Objects.equals(this.status, vpCNetworkRangeIPv6.status) &&
        Objects.equals(this.updatedAt, vpCNetworkRangeIPv6.updatedAt) &&
        Objects.equals(this.defaultPrefixLen, vpCNetworkRangeIPv6.defaultPrefixLen) &&
        Objects.equals(this.ipVersion, vpCNetworkRangeIPv6.ipVersion) &&
        Objects.equals(this.maxPrefixLen, vpCNetworkRangeIPv6.maxPrefixLen) &&
        Objects.equals(this.minPrefixLen, vpCNetworkRangeIPv6.minPrefixLen) &&
        Objects.equals(this.nameservers, vpCNetworkRangeIPv6.nameservers) &&
        Objects.equals(this.prefix, vpCNetworkRangeIPv6.prefix)&&
        Objects.equals(this.additionalProperties, vpCNetworkRangeIPv6.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(createdAt, description, id, labels, status, updatedAt, defaultPrefixLen, ipVersion, maxPrefixLen, minPrefixLen, nameservers, prefix, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VPCNetworkRangeIPv6 {\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    updatedAt: ").append(toIndentedString(updatedAt)).append("\n");
    sb.append("    defaultPrefixLen: ").append(toIndentedString(defaultPrefixLen)).append("\n");
    sb.append("    ipVersion: ").append(toIndentedString(ipVersion)).append("\n");
    sb.append("    maxPrefixLen: ").append(toIndentedString(maxPrefixLen)).append("\n");
    sb.append("    minPrefixLen: ").append(toIndentedString(minPrefixLen)).append("\n");
    sb.append("    nameservers: ").append(toIndentedString(nameservers)).append("\n");
    sb.append("    prefix: ").append(toIndentedString(prefix)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("createdAt", "description", "id", "labels", "status", "updatedAt", "defaultPrefixLen", "ipVersion", "maxPrefixLen", "minPrefixLen", "nameservers", "prefix"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(Arrays.asList("ipVersion", "prefix"));
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VPCNetworkRangeIPv6
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VPCNetworkRangeIPv6.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in VPCNetworkRangeIPv6 is not found in the empty JSON string", VPCNetworkRangeIPv6.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : VPCNetworkRangeIPv6.openapiRequiredFields) {
        if (jsonElement.getAsJsonObject().get(requiredField) == null) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field `%s` is not found in the JSON string: %s", requiredField, jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("description") != null && !jsonObj.get("description").isJsonNull()) && !jsonObj.get("description").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `description` to be a primitive type in the JSON string but got `%s`", jsonObj.get("description").toString()));
      }
      if ((jsonObj.get("id") != null && !jsonObj.get("id").isJsonNull()) && !jsonObj.get("id").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `id` to be a primitive type in the JSON string but got `%s`", jsonObj.get("id").toString()));
      }
      if ((jsonObj.get("status") != null && !jsonObj.get("status").isJsonNull()) && !jsonObj.get("status").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `status` to be a primitive type in the JSON string but got `%s`", jsonObj.get("status").toString()));
      }
      if (!jsonObj.get("ipVersion").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `ipVersion` to be a primitive type in the JSON string but got `%s`", jsonObj.get("ipVersion").toString()));
      }
      // OVERRIDE: this if block fixes oneOf issues
      if (!"ipv6".equals(jsonObj.get("ipVersion").getAsString())) {
        throw new IllegalArgumentException(
                String.format(
                        java.util.Locale.ROOT,
                        "Expectd the field `ipVersion` to have value `ipv6` but got `%s`",
                        jsonObj.get("ipVersion")
                )
        );
      }
      // validate the required field `ipVersion`
      IpVersionEnum.validateJsonElement(jsonObj.get("ipVersion"));
      // ensure the optional json data is an array if present
      if (jsonObj.get("nameservers") != null && !jsonObj.get("nameservers").isJsonNull() && !jsonObj.get("nameservers").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `nameservers` to be an array in the JSON string but got `%s`", jsonObj.get("nameservers").toString()));
      }
      if (!jsonObj.get("prefix").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `prefix` to be a primitive type in the JSON string but got `%s`", jsonObj.get("prefix").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VPCNetworkRangeIPv6.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VPCNetworkRangeIPv6' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VPCNetworkRangeIPv6> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VPCNetworkRangeIPv6.class));

       return (TypeAdapter<T>) new TypeAdapter<VPCNetworkRangeIPv6>() {
           @Override
           public void write(JsonWriter out, VPCNetworkRangeIPv6 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additional properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   JsonElement jsonElement = gson.toJsonTree(entry.getValue());
                   if (jsonElement.isJsonArray()) {
                     obj.add(entry.getKey(), jsonElement.getAsJsonArray());
                   } else {
                     obj.add(entry.getKey(), jsonElement.getAsJsonObject());
                   }
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public VPCNetworkRangeIPv6 read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             JsonObject jsonObj = jsonElement.getAsJsonObject();
             // store additional fields in the deserialized instance
             VPCNetworkRangeIPv6 instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VPCNetworkRangeIPv6 given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VPCNetworkRangeIPv6
   * @throws IOException if the JSON string is invalid with respect to VPCNetworkRangeIPv6
   */
  public static VPCNetworkRangeIPv6 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VPCNetworkRangeIPv6.class);
  }

  /**
   * Convert an instance of VPCNetworkRangeIPv6 to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

