name: Generate SDK
description: "Generates the Java SDK"
runs:
  using: "composite"
  steps:
    - name: Download OAS
      shell: bash
      run: make download-oas
    - name: Generate SDK
      shell: bash
      run: make generate-sdk LANGUAGE=java 