iaasV2ApiAreaId.path=iaas/v2api/model_area_id.go
iaasV2ApiAreaId.replacementPath=iaas/v2api/v2api_model_area_id.go
iaasV2ApiAreaId.hash=a97d25f94a504e19c6b988dd4029ea0c

iaasV1ApiAreaId.path=iaas/v1api/model_area_id.go
iaasV1ApiAreaId.replacementPath=iaas/v1api/v1api_model_area_id.go
iaasV1ApiAreaId.hash=0eefcbcb557da69c63de54138dcee90a

iaasV2BetaApiAreaId.path=iaas/v2beta1api/model_area_id.go
iaasV2BetaApiAreaId.replacementPath=iaas/v2beta1api/v2beta_model_area_id.go
iaasV2BetaApiAreaId.hash=f9943d639bdb4c0c804e233ef8eaa64a
