iaasV2ApiAreaId.path=iaas/v2api/model_area_id.go
iaasV2ApiAreaId.replacementPath=iaas/v2api/v2api_model_area_id.go
iaasV2ApiAreaId.hash=fd8a0426a8aefa66a10e7bb81c1cceba

iaasV1ApiAreaId.path=iaas/v1api/model_area_id.go
iaasV1ApiAreaId.replacementPath=iaas/v1api/v1api_model_area_id.go
iaasV1ApiAreaId.hash=b5626b52f7d93e9e9e26d679075d7031

iaasV2BetaApiAreaId.path=iaas/v2beta1api/model_area_id.go
iaasV2BetaApiAreaId.replacementPath=iaas/v2beta1api/v2beta_model_area_id.go
iaasV2BetaApiAreaId.hash=0e4f740cefba5981258cf15ecd995246
